'use client';
import {useState,useEffect,useRef} from 'react';
import {ScanLine,CheckCircle,Music2} from 'lucide-react';
export default function TicketView({token}:{token:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[scanning,setScanning]=useState(false),[busy,setBusy]=useState(false),[fresh,setFresh]=useState(false),[seconds,setSeconds]=useState(0);const video=useRef<HTMLVideoElement>(null),scanner=useRef<any>(null),sending=useRef(false);
 async function load(){try{const r=await fetch('/api/ticket/'+encodeURIComponent(token),{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load();return()=>{scanner.current?.destroy()}},[token]);
 useEffect(()=>{if(!fresh)return;const timer=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(timer)},[fresh]);
 async function check(raw:string){if(sending.current)return;let payload;try{payload=JSON.parse(raw);if(payload.site!==location.origin||typeof payload.gate!=='string')throw Error()}catch{setError('Please scan the Dandiya Night gate poster, not another QR.');return}sending.current=true;setBusy(true);scanner.current?.stop();setScanning(false);try{const r=await fetch('/api/ticket/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gate:payload.gate})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setData((old:any)=>({...old,ticket:{...old.ticket,...d.ticket}}));setSeconds(0);setFresh(true);setError('')}catch(e){setError((e as Error).message);await load()}finally{sending.current=false;setBusy(false)}}
 useEffect(()=>{if(!scanning||!video.current)return;let disposed=false;import('qr-scanner').then(async({default:QrScanner})=>{if(disposed||!video.current)return;const s=new QrScanner(video.current,(r)=>void check(r.data),{preferredCamera:'environment',highlightScanRegion:true,returnDetailedScanResult:true});scanner.current=s;try{await s.start();if(disposed)s.destroy()}catch{if(!disposed){setError('Camera access is unavailable. Allow camera access, or show your ticket link to the gate volunteer for check-in.');setScanning(false)}}}).catch(()=>{setError('Scanner could not load. Please ask the gate volunteer for check-in.');setScanning(false)});return()=>{disposed=true;scanner.current?.destroy();scanner.current=null}},[scanning]);
 const t=data?.ticket,ev=data?.event;const date=ev?.date?new Date(ev.date+':00+05:30').toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'})+' IST':'Date to be announced';
 return <main className="ticket-page"><div style={{textAlign:'center',marginBottom:24}}><Music2 style={{display:'inline',color:'#a32155'}}/><p className="eyebrow">YOUR INVITATION TO CELEBRATE</p></div>{error&&<div className="message" role="alert">{error}</div>}{loading?<p role="status">Opening your ticket…</p>:!data?<button className="primary" onClick={()=>{setLoading(true);void load()}}>Try again</button>:<>{t.entered_at?<section className={fresh&&seconds<60?'admitted':'panel'} aria-live="polite"><CheckCircle size={44} style={{margin:'0 auto 16px'}}/><h2>{fresh&&seconds<60?'Entry confirmed':'Already checked in'}</h2><p>{t.name}</p><div className="gate-stamp">{t.receipt}</div><p>{new Date(t.entered_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'medium',timeZone:'Asia/Kolkata'})} IST</p><p>{fresh&&seconds<60?`Show this to the volunteer now · ${seconds}s ago`:'This ticket has been used. It cannot admit another person.'}</p></section>:<section className="guest-ticket"><p className="eyebrow" style={{color:'#edbd74'}}>MUSIC · MOVEMENT · MEMORIES</p><h1>{ev?.name}</h1><p>ADMIT ONE</p><div className="details"><p className="guest">{t.name}</p><p>{date}</p><p>{ev?.venue}</p></div><p className="token">{t.token}</p>{t.cancelled?<div className="message" style={{color:'#7e1641'}}>This ticket has been cancelled.</div>:<><button className="primary no-print" disabled={busy||scanning} onClick={()=>{setError('');setScanning(true)}}><ScanLine size={20}/>{busy?'Checking entry…':'Scan the gate QR'}</button><p className="muted">At the entrance, scan the printed master QR and show the result to the volunteer.</p></>}</section>}{scanning&&<section className="panel no-print" style={{marginTop:20}}><h3>Point your camera at the gate QR</h3><video ref={video} muted playsInline/><button className="secondary" onClick={()=>setScanning(false)}>Close camera</button></section>}<p className="muted" style={{textAlign:'center'}}>One person · One entry<br/>Keep this personal ticket link private. Internet is required at the gate.</p>{!t.entered_at&&<button className="secondary no-print" onClick={()=>window.print()}>Save or print ticket</button>}</>}</main>
}
