import {manager,db,json,failure,body,str,defaults} from '@/lib/server';
import {admit,AppError} from '@/lib/ticket-service';
export async function GET(){try{const u=await manager();const event=await db().prepare('SELECT * FROM event WHERE id=1').first()||defaults;const tickets=await db().prepare('SELECT * FROM tickets ORDER BY created_at DESC').all();const team=u.isOwner?(await db().prepare('SELECT email FROM members ORDER BY email').all()).results:[];return json({event,tickets:tickets.results,team,user:{email:u.email,isOwner:u.isOwner}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{const u=await manager();const b=await body(req);switch(b.action){
 case 'event':{if(!u.isOwner)throw new AppError('Only the owner can edit the event.',403);const name=str(b.name,1,80),date=str(b.date,1,40),venue=str(b.venue,1,200);const price=Number(b.price);if(!Number.isFinite(price)||price<0||price>100000)throw new AppError('Enter a valid ticket price.');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(date))throw new AppError('Choose the event date and time.');await db().prepare('INSERT INTO event (id,name,date,venue,price,gate_key,gate_open) VALUES (1,?,?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET name=excluded.name,date=excluded.date,venue=excluded.venue,price=excluded.price').bind(name,date,venue,Math.round(price*100),crypto.randomUUID()+crypto.randomUUID()).run();return json({ok:true})}
 case 'issue':{const ev=await db().prepare('SELECT id FROM event WHERE id=1').first();if(!ev)throw new AppError('Save your event details before issuing tickets.');if(b.paid!==true)throw new AppError('Confirm that payment has been received.');const name=str(b.name,1,100),contact=str(b.contact||'',0,100),method=str(b.method,1,30);if(!['Cash','UPI / personal transfer','Other'].includes(method))throw new AppError('Choose a payment method.');const token=crypto.randomUUID();const requestId=str(b.requestId,36,36);if(!/^[0-9a-f-]{36}$/.test(requestId))throw new AppError('Invalid request ID.');await db().prepare('INSERT INTO tickets (token,name,contact,method,amount,issued_by,created_at,request_id,cancelled) SELECT ?,?,?,?,price,?,?,?,0 FROM event WHERE id=1 ON CONFLICT(request_id) DO NOTHING').bind(token,name,contact,method,u.email,new Date().toISOString(),requestId).run();const ticket=await db().prepare('SELECT * FROM tickets WHERE request_id=?').bind(requestId).first();return json({ticket})}
 case 'gate':{if(typeof b.open!=='boolean')throw new AppError('Choose open or closed.');const r=await db().prepare('UPDATE event SET gate_open=? WHERE id=1').bind(b.open?1:0).run();if(!r.meta.changes)throw new AppError('Save event details first.');return json({ok:true})}
 case 'admit':return json({ticket:await admit(db(),str(b.token,36,36),null,u.email)});
 case 'cancel':{const r=await db().prepare('UPDATE tickets SET cancelled=1 WHERE token=? AND entered_at IS NULL AND cancelled=0').bind(str(b.token,36,36)).run();if(!r.meta.changes)throw new AppError('Only unused, active tickets can be cancelled.',409);return json({ok:true})}
 case 'member':{if(!u.isOwner)throw new AppError('Only the owner can change the team.',403);const email=str(b.email,3,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AppError('Enter a valid email.');if(email===u.email.toLowerCase())throw new AppError('The owner already has access.');if(b.remove===true){await db().prepare('DELETE FROM members WHERE email=?').bind(email).run();return json({ok:true})}const r=await db().prepare('INSERT INTO members(email) SELECT ? WHERE (SELECT COUNT(*) FROM members)<4 ON CONFLICT(email) DO NOTHING').bind(email).run();if(!r.meta.changes)throw new AppError('This email is already added, or all four teammate places are full.');return json({ok:true})}
 default:throw new AppError('Unknown action.');}
}catch(e){return failure(e)}}
